<template>
  <footer class="footer d-flex flex-column align-items-center p-0">
    <div class="footer_join-section d-flex flex-column align-items-center">
      <div
        class="
          footer_join-section_container
          d-flex
          flex-column
          align-items-start
        "
      >
        <div
          class="
            footer_join-section_container_content
            d-flex
            flex-row
            align-items-center
            p-0
          "
        >
          <div
            class="
              footer_join-section_container_content_text-and-support
              d-flex
              flex-column
              align-items-start
              p-0
            "
          >
            <p
              class="
                footer_join-section_container_content_text-and-support_text
              "
            >
              Join our newsletter
            </p>
            <p
              class="
                footer_join-section_container_content_text-and-support_support
              "
            >
              Banking technology that has your back.
            </p>
          </div>
          <div
            class="
              footer_join-section_container_content_email-capture
              d-flex
              flex-row
              align-items-start
              p-0
            "
          >
            <div
              class="
                footer_join-section_container_content_email-capture_input-field
                d-flex
                flex-column
                align-items-start
                p-0
              "
            >
              <div
                class="
                  footer_join-section_container_content_email-capture_input-field_input-container
                  d-flex
                  flex-column
                  align-items-start
                  p-0
                "
              >
                <input
                  placeholder="Enter your email"
                  class="
                    footer_join-section_container_content_email-capture_input-field_input-container_input
                    d-flex
                    flex-row
                    align-items-center
                  "
                  type="text"
                >
              </div>
            </div>
            <button
              class="
                footer_join-section_container_content_email-capture_btn
                d-flex
                justify-content-center
                align-items-center
              "
            >
              <span
                class="
                  footer_join-section_container_content_email-capture_btn_btn-text
                "
              >Subscribe</span>
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="footer_links-section d-flex flex-column align-items-center">
      <div
        class="
          footer_links-section_link-container
          d-flex
          flex-column
          align-items-start
        "
      >
        <div
          class="
            footer_links-section_link-container_content
            d-flex
            flex-row
            align-items-start
            p-0
          "
        >
          <div
            class="
              footer_links-section_link-container_content_logo-and-supporting
              d-flex
              flex-column
              align-items-start
              p-0
            "
          >
            <div
              class="
                footer_links-section_link-container_content_logo-and-supporting_logo
                d-flex
                flex-row
                align-items-start
                p-0
              "
            >
              <span
                class="
                  footer_links-section_link-container_content_logo-and-supporting_logo_logo-text
                "
              >
                { } Bordo Blog
              </span>
            </div>
            <div
              class="
                footer_links-section_link-container_content_logo-and-supporting_supporting
              "
            >
              Design amazing digital experiences that create more happy in the
              world.
            </div>
          </div>
          <div
            class="
              footer_links-section_link-container_content_links
              d-flex
              flex-row
              align-items-start
              p-0
            "
          >
            <div
              class="
                footer_links-section_link-container_content_links_link-column
                d-flex
                flex-column
                align-items-start
                p-0
              "
            >
              <span
                class="
                  footer_links-section_link-container_content_links_link-column_heading
                "
              >Product</span>
              <div
                class="
                  footer_links-section_link-container_content_links_link-column_footer-links
                  d-flex
                  flex-column
                  align-items-start
                  p-0
                "
              >
                <div
                  class="
                    footer_links-section_link-container_content_links_link-column_footer-links_footer-link
                    d-flex
                    flex-row
                    align-items-center
                    p-0
                  "
                >
                  Overview
                </div>
                <div
                  class="
                    footer_links-section_link-container_content_links_link-column_footer-links_footer-link
                    d-flex
                    flex-row
                    align-items-center
                    p-0
                  "
                >
                  Features
                </div>
                <div
                  class="
                    footer_links-section_link-container_content_links_link-column_footer-links_footer-link
                    d-flex
                    flex-row
                    align-items-center
                    p-0
                  "
                >
                  Solutions
                  <div class="badge d-flex flex-row align-items-start p-0">
                    <div
                      class="
                        badge_base
                        d-flex
                        flex-row
                        justify-content-center
                        align-items-center
                      "
                    >
                      <span class="badge_base_text">New</span>
                    </div>
                  </div>
                </div>
                <div
                  class="
                    footer_links-section_link-container_content_links_link-column_footer-links_footer-link
                    d-flex
                    flex-row
                    align-items-center
                    p-0
                  "
                >
                  Tutorials
                </div>
                <div
                  class="
                    footer_links-section_link-container_content_links_link-column_footer-links_footer-link
                    d-flex
                    flex-row
                    align-items-center
                    p-0
                  "
                >
                  Pricing
                </div>
                <div
                  class="
                    footer_links-section_link-container_content_links_link-column_footer-links_footer-link
                    d-flex
                    flex-row
                    align-items-center
                    p-0
                  "
                >
                  Releases
                </div>
              </div>
            </div>
            <div
              v-for="i in 4"
              :key="i"
              class="
                footer_links-section_link-container_content_links_link-column
                d-flex
                flex-column
                align-items-start
                p-0
              "
            >
              <span
                class="
                  footer_links-section_link-container_content_links_link-column_heading
                "
              >Product</span>
              <div
                class="
                  footer_links-section_link-container_content_links_link-column_footer-links
                  d-flex
                  flex-column
                  align-items-start
                  p-0
                "
              >
                <div
                  class="
                    footer_links-section_link-container_content_links_link-column_footer-links_footer-link
                    d-flex
                    flex-row
                    align-items-center
                    p-0
                  "
                >
                  Overview
                </div>
                <div
                  class="
                    footer_links-section_link-container_content_links_link-column_footer-links_footer-link
                    d-flex
                    flex-row
                    align-items-center
                    p-0
                  "
                >
                  Features
                </div>
                <div
                  class="
                    footer_links-section_link-container_content_links_link-column_footer-links_footer-link
                    d-flex
                    flex-row
                    align-items-center
                    p-0
                  "
                >
                  Solutions
                </div>
                <div
                  class="
                    footer_links-section_link-container_content_links_link-column_footer-links_footer-link
                    d-flex
                    flex-row
                    align-items-center
                    p-0
                  "
                >
                  Tutorials
                </div>
                <div
                  class="
                    footer_links-section_link-container_content_links_link-column_footer-links_footer-link
                    d-flex
                    flex-row
                    align-items-center
                    p-0
                  "
                >
                  Pricing
                </div>
                <div
                  class="
                    footer_links-section_link-container_content_links_link-column_footer-links_footer-link
                    d-flex
                    flex-row
                    align-items-center
                    p-0
                  "
                >
                  Releases
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div
        class="
          footer_links-section_social-container
          d-flex
          flex-column
          align-items-start
        "
      >
        <div
          class="
            footer_links-section_social-container_content
            d-flex
            flex-row
            align-items-center
          "
        >
          <span
            class="footer_links-section_social-container_content_footer-text"
          >@ 2022 Bordo.io All rights reserved.</span>
          <div
            class="
              footer_links-section_social-container_content_social-icons
              d-flex
              flex-row
              align-items-center
              p-0
            "
          >
            <div
              class="
                footer_links-section_social-container_content_social-icons_social-icon
              "
            >
              <ion-icon
                name="logo-twitter"
                class="
                  footer_links-section_social-container_content_social-icons_social-icon_icon
                "
              />
            </div>
            <div
              class="
                footer_links-section_social-container_content_social-icons_social-icon
              "
            >
              <ion-icon
                name="logo-linkedin"
                class="
                  footer_links-section_social-container_content_social-icons_social-icon_icon
                "
              />
            </div>

            <div
              class="
                footer_links-section_social-container_content_social-icons_social-icon
              "
            >
              <ion-icon
                name="logo-facebook"
                class="
                  footer_links-section_social-container_content_social-icons_social-icon_icon
                "
              />
            </div>

            <div
              class="
                footer_links-section_social-container_content_social-icons_social-icon
              "
            >
              <ion-icon
                name="logo-github"
                class="
                  footer_links-section_social-container_content_social-icons_social-icon_icon
                "
              />
            </div>

            <div
              class="
                footer_links-section_social-container_content_social-icons_social-icon
              "
            >
              <ion-icon
                name="basketball-outline"
                class="
                  footer_links-section_social-container_content_social-icons_social-icon_icon
                "
              />
            </div>
            <div
              class="
                footer_links-section_social-container_content_social-icons_social-icon
              "
            >
              <ion-icon
                name="boat-outline"
                class="
                  footer_links-section_social-container_content_social-icons_social-icon_icon
                "
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>

<script>
export default {
  name: 'TheFooter'
}
</script>
