<template>
  <section
    class="
      quote
      d-flex
      flex-column
      justify-content-center
      align-items-center
      order-6
    "
  >
    <div
      class="
        quote_container
        d-flex
        flex-row
        justify-content-center
        align-items-center
        order-0
      "
    >
      <div
        class="
          quote_container_content
          d-flex
          flex-row
          align-items-center
          p-0
          order-0
        "
      >
        <div
          class="
            quote_container_content_text-content
            d-flex
            flex-column
            align-items-start
            justify-content-center
          "
        >
          <div
            class="
              quote_container_content_text-content_quote-and-attr
              d-flex
              flex-column
              align-items-start
              p-0
              order-0
            "
          >
            <div
              class="
                quote_container_content_text-content_quote-and-attr_quote-and-stars
                d-flex
                flex-column
                align-items-start
                p-0
                order-0
              "
            >
              <div
                class="
                  quote_container_content_text-content_quote-and-attr_quote-and-stars_stars
                  d-flex
                  flex-row
                  align-items-center
                  p-0
                  order-0
                "
              >
                <div
                  class="
                    quote_container_content_text-content_quote-and-attr_quote-and-stars_stars_star-icon
                  "
                >
                  <ion-icon
                    class="
                      quote_container_content_text-content_quote-and-attr_quote-and-stars_stars_star-icon_icon
                    "
                    name="star"
                  />
                </div>
                <div
                  class="
                    quote_container_content_text-content_quote-and-attr_quote-and-stars_stars_star-icon
                  "
                >
                  <ion-icon
                    class="
                      quote_container_content_text-content_quote-and-attr_quote-and-stars_stars_star-icon_icon
                    "
                    name="star"
                  />
                </div>
                <div
                  class="
                    quote_container_content_text-content_quote-and-attr_quote-and-stars_stars_star-icon
                  "
                >
                  <ion-icon
                    class="
                      quote_container_content_text-content_quote-and-attr_quote-and-stars_stars_star-icon_icon
                    "
                    name="star"
                  />
                </div>
                <div
                  class="
                    quote_container_content_text-content_quote-and-attr_quote-and-stars_stars_star-icon
                  "
                >
                  <ion-icon
                    class="
                      quote_container_content_text-content_quote-and-attr_quote-and-stars_stars_star-icon_icon
                    "
                    name="star"
                  />
                </div>
                <div
                  class="
                    quote_container_content_text-content_quote-and-attr_quote-and-stars_stars_star-icon
                  "
                >
                  <ion-icon
                    class="
                      quote_container_content_text-content_quote-and-attr_quote-and-stars_stars_star-icon_icon
                    "
                    name="star"
                  />
                </div>
              </div>
              <p
                class="
                  quote_container_content_text-content_quote-and-attr_quote-and-stars_quote
                "
              >
                Love the simplicity of the service and the prompt customer
                support. We can't imagine working without it.
              </p>
            </div>

            <div
              class="
                quote_container_content_text-content_quote-and-attr_text-and-support
                d-flex
                flex-column
                align-items-start
                p-0
                order-1
              "
            >
              <span
                class="
                  quote_container_content_text-content_quote-and-attr_text-and-support_text
                "
              >— Renee Wells</span>
              <span
                class="
                  quote_container_content_text-content_quote-and-attr_text-and-support_support
                "
              >Product Designer, Quotient</span>
            </div>
            <div
              class="
                quote_container_content_text-content_quote-and-attr_pagination
                d-flex
                flex-row
                justify-content-center
                align-items-center
                p-0
              "
            >
              <div
                class="
                  quote_container_content_text-content_quote-and-attr_pagination_dot
                "
              />
              <div
                class="
                  quote_container_content_text-content_quote-and-attr_pagination_dot
                "
              />
              <div
                class="
                  quote_container_content_text-content_quote-and-attr_pagination_dot
                "
              />
            </div>
          </div>
        </div>
        <div class="quote_container_content_image" />
      </div>
    </div>
  </section>
</template>

<script>
export default { name: 'QuoteSection' }
</script>

<style lang="scss" scoped></style>
